FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm ci

# Next.js telemetry
ENV NEXT_TELEMETRY_DISABLED 1

# Expose port
EXPOSE 3000

# Use npx to run next directly from node_modules
CMD ["npx", "next", "dev", "-H", "0.0.0.0"] 