version: '3.8'

services:
  # Backend service
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb+srv://dogukannakin:KQg7XLdzN19mpKWo@cluster0.2remq.mongodb.net/todoapp?retryWrites=true&w=majority&connectTimeoutMS=30000&socketTimeoutMS=45000
      - JWT_SECRET=YWkk9ZUndoewS7dRbvaX4yOyYZapn2C7ihtDJ6n4kNk=
      - JWT_EXPIRES_IN=7d
      - OPENAI_API_KEY=sk-m2f-kHMSAzjSxKXJiK2MTekH10KWmUmkFEQ_H3ZN7iT3BlbkFJtccwF2okbZE71plN6EBkseNjSGePXxNsmBS8bfvW8A
    depends_on:
      - mongodb
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    networks:
      - app-network
    command: sh -c "npm run build && npm start"

  # MongoDB service
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge 